plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  httpapi: {}
  inventory: {}
  lookup: {}
  module:
    hpe_nimble_access_control_record:
      description: Manage the HPE Nimble Storage access control records.
      name: hpe_nimble_access_control_record
      namespace: ''
      version_added: 2.9.0
    hpe_nimble_array:
      description: Manage the HPE Nimble Storage array.
      name: hpe_nimble_array
      namespace: ''
      version_added: 2.9.0
    hpe_nimble_chap_user:
      description: Manage the HPE Nimble Storage CHAP user.
      name: hpe_nimble_chap_user
      namespace: ''
      version_added: 2.9.0
    hpe_nimble_disk:
      description: Manage the HPE Nimble Storage disk.
      name: hpe_nimble_disk
      namespace: ''
      version_added: 2.9.0
    hpe_nimble_encryption:
      description: Manage the HPE Nimble Storage encryption.
      name: hpe_nimble_encryption
      namespace: ''
      version_added: 2.9.0
    hpe_nimble_fc:
      description: Manage the HPE Nimble Storage Fibre Channel.
      name: hpe_nimble_fc
      namespace: ''
      version_added: 2.9.0
    hpe_nimble_group:
      description: Manage the HPE Nimble Storage group.
      name: hpe_nimble_group
      namespace: ''
      version_added: 2.9.0
    hpe_nimble_info:
      description: Collect information from HPE Nimble Storage array.
      name: hpe_nimble_info
      namespace: ''
      version_added: 2.9.0
    hpe_nimble_initiator_group:
      description: Manage the HPE Nimble Storage initiator groups.
      name: hpe_nimble_initiator_group
      namespace: ''
      version_added: 2.9.0
    hpe_nimble_network:
      description: Manage the HPE Nimble Storage network configuration.
      name: hpe_nimble_network
      namespace: ''
      version_added: 2.9.0
    hpe_nimble_partner:
      description: Manage the HPE Nimble Storage Replication Partner.
      name: hpe_nimble_partner
      namespace: ''
      version_added: 2.9.0
    hpe_nimble_performance_policy:
      description: Manage the HPE Nimble Storage performance policies
      name: hpe_nimble_performance_policy
      namespace: ''
      version_added: 2.9.0
    hpe_nimble_pool:
      description: Manage the HPE Nimble Storage pools.
      name: hpe_nimble_pool
      namespace: ''
      version_added: 2.9.0
    hpe_nimble_protection_schedule:
      description: Manage the HPE Nimble Storage protection schedules.
      name: hpe_nimble_protection_schedule
      namespace: ''
      version_added: 2.9.0
    hpe_nimble_protection_template:
      description: Manage the HPE Nimble Storage protection templates.
      name: hpe_nimble_protection_template
      namespace: ''
      version_added: 2.9.0
    hpe_nimble_shelf:
      description: Manage the HPE Nimble Storage shelves.
      name: hpe_nimble_shelf
      namespace: ''
      version_added: 2.9.0
    hpe_nimble_snapshot:
      description: Manage the HPE Nimble Storage snapshots.
      name: hpe_nimble_snapshot
      namespace: ''
      version_added: 2.9.0
    hpe_nimble_snapshot_collection:
      description: Manage the HPE Nimble Storage snapshot collections.
      name: hpe_nimble_snapshot_collection
      namespace: ''
      version_added: 2.9.0
    hpe_nimble_user:
      description: Manage the HPE Nimble Storage users.
      name: hpe_nimble_user
      namespace: ''
      version_added: 2.9.0
    hpe_nimble_user_policy:
      description: Manage the HPE Nimble Storage user policies.
      name: hpe_nimble_user_policy
      namespace: ''
      version_added: 2.9.0
    hpe_nimble_volume:
      description: Manage the HPE Nimble Storage volumes.
      name: hpe_nimble_volume
      namespace: ''
      version_added: 2.9.0
    hpe_nimble_volume_collection:
      description: Manage the HPE Nimble Storage volume collections.
      name: hpe_nimble_volume_collection
      namespace: ''
      version_added: 2.9.0
  netconf: {}
  shell: {}
  strategy: {}
  vars: {}
version: 1.0.0
